[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
f44 = "EU3VeefFYGqLKc6s1W7XBhPSvV2nMQgETfJ2fRc858ii"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/f44.ts"

