[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
f44 = "C67YgrXJvyN9AY8jE6yLccNDNfNxg9LKS7LTJDKsMqnv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/f44.ts"

